# Generated by Django 5.1.4 on 2024-12-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
