# Generated by Django 5.1.4 on 2024-12-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(default='Não informado', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default='Não informada', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.CharField(default='Não informado', max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='Não informado', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uf',
            field=models.CharField(default='UF', max_length=2),
        ),
    ]
