# Generated by Django 5.1.4 on 2024-12-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_remove_cliente_endereco_cliente_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedora',
            name='contrato',
            field=models.FileField(blank=True, null=True, upload_to='contratos/'),
        ),
    ]
