# Generated by Django 5.1.4 on 2025-01-18 21:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_vendedora_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Acerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=10)),
                ('data_pedido', models.DateField()),
                ('data_acerto', models.DateField()),
                ('cidade', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendedora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acertos', to='setup.vendedora')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='setup.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='EstoqueVendedora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.produto')),
                ('vendedora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.vendedora')),
            ],
            options={
                'unique_together': {('vendedora', 'produto')},
            },
        ),
        migrations.AddField(
            model_name='vendedora',
            name='produtos',
            field=models.ManyToManyField(through='setup.EstoqueVendedora', to='setup.produto'),
        ),
        migrations.CreateModel(
            name='ItemAcerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='setup.acerto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='setup.compra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.produto')),
            ],
        ),
    ]
