# Generated by Django 5.1.4 on 2025-01-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0010_alter_produto_quantidade_acerto_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acerto',
            name='comissao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
